apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: ibm-blockchain-platform-psp-clusterrole-211
rules:
- apiGroups:
  - extensions
  resourceNames:
  - ibm-blockchain-platform-psp-211
  resources:
  - podsecuritypolicies
  verbs:
  - use
